#!/bin/sh

systemDir=/usr/local/sbin/
permissions=755

sourceDir=$(echo $0 | sed -r 's/install$//')
allScripts=`ls $sourceDir|grep -Evi 'licence|license|install'`

for script in ${allScripts[*]}
do
    cp -f $sourceDir$script $systemDir$script
    chmod $permissions $systemDir$script
done
