#!/bin/bash

printUsage() {
    echo "Usage: " `echo $0|rev|cut -d '/' -f1|rev` " [options] id"
    echo "Prepare environment for chroot and enter it"
    echo "The chroot environment will be located at /mnt/<id>;
the root dyrectory and other non-standar directories must be present in fstab, or be properly mounted before executing this script"
    echo "Options:
-h: print this help and exit
-v: print version and exit"
}

printVersion() {
    version="1.0"
    echo `echo $0|rev|cut -d '/' -f1|rev` " version $version."
    echo "This software is released in public domain, see \"LICENSE\" for further details."
}

id=$1
bkdir=$2

while getopts hv: options
do
    case $options in
	h) printUsage
	   exit 0;;
	v)printVersion
          exit 0;;
    esac
done


if [[ -z $1 ]]
then
    echo id argument required
    exit 1
fi

# mount relevant directories listed in fstab
for mp in `grep "/mnt/$1" /etc/fstab|sed 's/[[:space:]]\+/:/g'`
do
    args=(`echo $mp|sed 's/:/ /g'`)
    echo ${args[1]}
    mount ${args[1]}
done

# mount some standard directories
mount -t proc proc /mnt/$1/proc
for i in sys dev /dev/pts /run/shm
do
mount -B $i /mnt/$1/$i
done
for i in sys dev
do
mount --make-rslave /mnt/$1/$i
done

# a few systems require this
mkdir /mnt/$1/run/shm

# these directories are by default in PATH only in certain distributions; add them
PATH=$PATH:/bin:/sbin:/usr/local/bin:/usr/local/sbin

#makes the network available after chrooting
mkdir /mnt/$1/run/resolvconf
cp -f /etc/resolv.conf /mnt/$1/etc/
cp /etc/resolv.conf /mnt/$1/run/systemd/resolve/
cp /etc/resolv.conf /mnt/$1/run/resolvconf/

# chroot
chroot /mnt/$1
